# Generated by Django 3.2.21 on 2023-11-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='excerpt',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.TextField(blank=True),
        ),
    ]
