# Generated by Django 3.2.21 on 2023-11-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20231102_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='excerpt',
            new_name='method',
        ),
    ]
